# Generated by Django 5.1.4 on 2025-01-01 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='product_validity',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
