# Generated by Django 5.1.4 on 2025-01-01 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_app', '0002_product_product_status_product_product_validity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_status',
            field=models.BooleanField(default=True),
        ),
    ]
